export const projects = [
    {
      id: 1,
      name: "PriceBreaker Travel",
      url: "https://www.pricebreaker.travel/",
      photo: "/project-photos/pricebreaker.png",
      logo: "/project-photos/logos/pricebreaker.svg",
    },
    {
      id: 2,
      name: "PlanTrip",
      url: "https://www.plantrip.sg/",
      photo: "/project-photos/plantrip.png",
      logo: "/project-photos/logos/plantriplogo.png",
    },
    {
      id: 3,
      name: "Go Where Do What",
      url: "https://www.gowheredowhat.sg/",
      photo: "/project-photos/gwdw.png",
      logo: "/project-photos/logos/gwdw.png",
    },
    {
      id: 4,
      name: "NATAS Travel Fairs",
      url: "https://www.natastravelfair.travel/",
      photo: "/project-photos/natas.png",
      logo: "/project-photos/logos/natas.png",
    },
    {
      id: 5,
      name: "China Express",
      url: "https://www.chinaexpress.com.sg/",
      photo: "/project-photos/chinaexpress.png",
    },
    {
      id: 6,
      name: "RoyalWings",
      url: "https://royalwingstravel.com.sg/",
      photo: "/project-photos/royalwings.png",
      logo: "/project-photos/logos/royalwingslogo.png",
    },
    {
      id: 7,
      name: "REET Travel",
      url: "https://www.reet.travel/",
      photo: "/project-photos/reet.png",
    },
    {
      id: 8,
      name: "Worldpass Holidays",
      url: "https://worldpassholidays.com/",
      photo: "/project-photos/worldpass.png",
    },
    {
      id: 9,
      name: "ILoveKorea",
      url: "https://ilovekorea.tours/",
      photo: "/project-photos/ilovekorea.png",
    },
    {
      id: 10,
      name: "Planet Travel",
      url: "https://www.planettravel.com.sg/",
      photo: "/project-photos/planettravel.png",
    },
    {
      id: 11,
      name: "Silkway Travel Asia",
      url: "https://www.silkwaytravelasia.com/",
      photo: "/project-photos/silkway.png",
    },
    {
      id: 12,
      name: "Karana Travel",
      url: "https://karana.com.sg/",
      photo: "/project-photos/karana.png",
    },
    {
      id: 13,
      name: "New Star Travel",
      url: "https://newstar.com.sg/",
      photo: "/project-photos/newstars.png",
    },
    {
      id: 14,
      name: "Pegasus Travel Solution",
      url: "https://pegasustravel.com.sg/",
      photo: "/project-photos/pegasus.png",
    },
    {
      id: 15,
      name: "Azure Holidays",
      url: "https://www.azureholidays.sg/",
      photo: "/project-photos/azureholidays.png",
    },
    {
      id: 16,
      name: "Rere Travel Planners",
      url: "https://www.reretravelplanners.com/",
      photo: "/project-photos/reretravel.png",
    },
    {
      id: 17,
      name: "Splendour Holidays",
      url: "https://www.splendour.com.sg/",
      photo: "/project-photos/splendour.png",
    },
    {
      id: 18,
      name: "Easy Ticket Holidays",
      url: "https://www.easyticketsholidays.com/",
      photo: "/project-photos/easyticket.png",
    },
    {
      id: 19,
      name: "Oriental Travel & Tours ",
      url: "https://www.orientaltours.com.sg/",
      photo: "/project-photos/oriental.png",
    },
    {
      id: 20,
      name: "Rere Travel Planners",
      url: "https://www.reretravelplanners.com/",
      photo: "/project-photos/reretravel.png",
    },
    {
      id: 21,
      name: "1896 Travel",
      url: "https://www.1896travel.com/",
      photo: "/project-photos/1896.png",
    },
    {
      id: 22,
      name: "ExprienCEE Travel",
      url: "https://cee.travel/",
      photo: "/project-photos/cee.png",
    },
    {
      id: 23,
      name: "Jie Yun Tong Travel",
      url: "https://www.jieyuntong.com.sg/",
      photo: "/project-photos/jytong.png",
    },
    {
      id: 24,
      name: "M.I.C.E matters",
      url: "https://www.micematters.com/",
      photo: "/project-photos/micematters.png",
    },
  ];