import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useEffect, useRef, useState } from "react";
import AboutMe from "@/components/AboutMe";
import {
  InstagramOutlined,
  GithubOutlined,
  LinkedinOutlined,
  MailOutlined,
} from "@ant-design/icons";
import MyProjects from "@/components/MyProjects";
import { projects } from "../../public/data";
import { easeInOut, motion } from "framer-motion";

export default function Home() {
  const [changeColor, setChangeColor] = useState(false);
  const [slideUp, setSlideUp] = useState(false);

  useEffect(() => {
    const intervalId = setInterval(() => {
      setChangeColor((prevState) => !prevState);
    }, 5000);
    return () => clearInterval(intervalId);
  }, []);

  useEffect(() => {
    const interval = setInterval(() => {
      setSlideUp(true);
    }, 800);
  }, []);

  return (
    <>
      <Head>
        <title>Aye Sandar Min | Protfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* eslint-disable-next-line @next/next/no-page-custom-font */}
        <link
          href="https://fonts.googleapis.com/css2?family=Outfit:wght@100;200;300;400;700&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <motion.main
        className={`${styles.main}`}
        initial={{ y: 60, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        exit={{ y: -10, opacity: 0 }}
        transition={{ duration: 0.8 }}
      >
        <div className={styles.introWrapper}>
          <div className={styles.intro}>
            <h4>Hello,</h4>
            <h1>
              I&apos;m Aye<span>!</span>
            </h1>
            <p>
              I <span>specialize</span> in building exceptional and accessible
              digital experiences <br /> for{" "}
              <span>websites and web applications</span>,
              <br /> bringing <span>creativity</span> and{" "}
              <span>functionality</span> together seamlessly.
            </p>
            {/* <p>
              A frontend developer with a passion for <br /> transforming
              websites and web applications into <br /> stunning visual
              experiences!
            </p> */}
            <div className={styles.socialIconsWrapper}>
              <div className={styles.socialIcon}>
                <a href="https://github.com/AyeSandarMin" target="_blank">
                  <GithubOutlined />
                </a>
              </div>
              <div className={styles.socialIcon}>
                <a
                  href="https://www.linkedin.com/in/aye-sandar-min/"
                  target="_blank"
                >
                  <LinkedinOutlined />
                </a>
              </div>
              <div className={styles.socialIcon}>
                <a href="https://www.instagram.com/__ayesdm__/" target="_blank">
                  <InstagramOutlined />
                </a>
              </div>
              <div className={styles.socialIcon}>
                <a href="mailto:ayesandarmin.dev@gmail.com">
                  <MailOutlined />
                </a>
              </div>
            </div>
          </div>
          <div style={{ position: "relative" }}>
            <motion.div
              // className={styles.box}
              className={`${styles.avatarWrapper} ${
                slideUp ? styles.slideUp : ""
              } ${changeColor ? styles.changeColor : ""}`}
              initial={{ y: 10, opacity: 0 }}
              animate={{ y: 0, opacity: 1 }}
              exit={{ y: -10, opacity: 0 }}
              transition={{ duration: 0.2 }}
            >
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <motion.img
                src="/rounded-avatar.png"
                width={420}
                height={420}
                className={styles.avatarImg}
                alt="avatar"
                initial={{ y: 10, opacity: 0 }}
                animate={{ y: 0, opacity: 1 }}
                exit={{ y: -10, opacity: 0 }}
                transition={{ duration: 0.2 }}
              />
            </motion.div>

            {/* <div className={styles.hiddenBg}></div> */}
          </div>
          {/* <div className={styles.container}>
            <div className={styles.slideUp}>
              <img
                src="/profile-avatar.png"
                width={200}
                height={200}
                style={{ marginTop: "-5px" }}
              />
            </div>
          </div> */}
        </div>
        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true, amount: 0.1 }}
          transition={{ duration: 1, delay: 0.3 }}
        >
          <AboutMe />
        </motion.div>

        <motion.div
          initial={{ opacity: 1 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true, amount: 0.8 }}
          transition={{ duration: 1, delay: 0.8 }}
          style={{ width: "100%" }}
        >
          <MyProjects projects={projects} />
        </motion.div>
      </motion.main>
    </>
  );
}
